version: '3'
services:
  mongo:
    container_name: mongoDB
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017

    volumes:
      - ./data:/data/db
      - ./data:/data/configdb
